package com.tiyiyun.sso.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.tiyiyun.sso.entity.AlipayUserInfoEntity;

@Mapper
public interface AlipayUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alipay_user_info
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    long countByExample(AlipayUserInfoEntity example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alipay_user_info
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    int deleteByExample(AlipayUserInfoEntity example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alipay_user_info
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alipay_user_info
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    int insert(AlipayUserInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alipay_user_info
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    int insertSelective(AlipayUserInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alipay_user_info
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    List<AlipayUserInfoEntity> selectByExample(AlipayUserInfoEntity example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alipay_user_info
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    AlipayUserInfoEntity selectByPrimaryKey(Long id);
    
    AlipayUserInfoEntity findByOpenId(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alipay_user_info
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    int updateByExampleSelective(@Param("record") AlipayUserInfoEntity record, @Param("example") AlipayUserInfoEntity example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alipay_user_info
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    int updateByExample(@Param("record") AlipayUserInfoEntity record, @Param("example") AlipayUserInfoEntity example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alipay_user_info
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    int updateByPrimaryKeySelective(AlipayUserInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alipay_user_info
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    int updateByPrimaryKey(AlipayUserInfoEntity record);
}