package com.tiyiyun.sso.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.tiyiyun.sso.entity.AppEntity;

@Mapper
public interface AppMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app
     *
     * @mbg.generated Fri Mar 10 03:27:58 UTC 2023
     */
    long countByExample(AppEntity example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app
     *
     * @mbg.generated Fri Mar 10 03:27:58 UTC 2023
     */
    int deleteByExample(AppEntity example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app
     *
     * @mbg.generated Fri Mar 10 03:27:58 UTC 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app
     *
     * @mbg.generated Fri Mar 10 03:27:58 UTC 2023
     */
    int insert(AppEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app
     *
     * @mbg.generated Fri Mar 10 03:27:58 UTC 2023
     */
    int insertSelective(AppEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app
     *
     * @mbg.generated Fri Mar 10 03:27:58 UTC 2023
     */
    List<AppEntity> selectByExample(AppEntity example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app
     *
     * @mbg.generated Fri Mar 10 03:27:58 UTC 2023
     */
    AppEntity selectByPrimaryKey(String appId);
    
    AppEntity selectByAppIdAndAppSec(@Param("appId") String appId, @Param("appSecret") String appSecret);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app
     *
     * @mbg.generated Fri Mar 10 03:27:58 UTC 2023
     */
    int updateByExampleSelective(@Param("record") AppEntity record, @Param("example") AppEntity example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app
     *
     * @mbg.generated Fri Mar 10 03:27:58 UTC 2023
     */
    int updateByExample(@Param("record") AppEntity record, @Param("example") AppEntity example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app
     *
     * @mbg.generated Fri Mar 10 03:27:58 UTC 2023
     */
    int updateByPrimaryKeySelective(AppEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app
     *
     * @mbg.generated Fri Mar 10 03:27:58 UTC 2023
     */
    int updateByPrimaryKey(AppEntity record);
}