package com.tiyiyun.sso.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.smart.sso.client.entity.UserInfoEntity;


@Mapper
public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_UserInfoEntity_info
     *
     * @mbg.generated Fri Mar 10 03:08:04 UTC 2023
     */
    long countByExample(UserInfoEntity example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_UserInfoEntity_info
     *
     * @mbg.generated Fri Mar 10 03:08:04 UTC 2023
     */
    int deleteByExample(UserInfoEntity example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_UserInfoEntity_info
     *
     * @mbg.generated Fri Mar 10 03:08:04 UTC 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_UserInfoEntity_info
     *
     * @mbg.generated Fri Mar 10 03:08:04 UTC 2023
     */
    int insert(UserInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_UserInfoEntity_info
     *
     * @mbg.generated Fri Mar 10 03:08:04 UTC 2023
     */
    int insertSelective(UserInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_UserInfoEntity_info
     *
     * @mbg.generated Fri Mar 10 03:08:04 UTC 2023
     */
    List<UserInfoEntity> selectByExample(UserInfoEntity example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_UserInfoEntity_info
     *
     * @mbg.generated Fri Mar 10 03:08:04 UTC 2023
     */
    UserInfoEntity selectByPrimaryKey(Long id);
    
    UserInfoEntity findBySubId(Long subId);
    
    UserInfoEntity findByDeviceNo(String deviceNo);
    
    UserInfoEntity selectByUserNameAndPass(@Param("deviceNo") String deviceNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_UserInfoEntity_info
     *
     * @mbg.generated Fri Mar 10 03:08:04 UTC 2023
     */
    int updateByExampleSelective(@Param("record") UserInfoEntity record, @Param("example") UserInfoEntity example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_UserInfoEntity_info
     *
     * @mbg.generated Fri Mar 10 03:08:04 UTC 2023
     */
    int updateByExample(@Param("record") UserInfoEntity record, @Param("example") UserInfoEntity example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_UserInfoEntity_info
     *
     * @mbg.generated Fri Mar 10 03:08:04 UTC 2023
     */
    int updateByPrimaryKeySelective(UserInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_UserInfoEntity_info
     *
     * @mbg.generated Fri Mar 10 03:08:04 UTC 2023
     */
    int updateByPrimaryKey(UserInfoEntity record);
}