package com.tiyiyun.sso.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.smart.sso.client.entity.WxUserInfoEntity;


@Mapper
public interface WxUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user_info
     *
     * @mbg.generated Fri May 12 05:53:46 UTC 2023
     */
    long countByExample(WxUserInfoEntity example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user_info
     *
     * @mbg.generated Fri May 12 05:53:46 UTC 2023
     */
    int deleteByExample(WxUserInfoEntity example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user_info
     *
     * @mbg.generated Fri May 12 05:53:46 UTC 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user_info
     *
     * @mbg.generated Fri May 12 05:53:46 UTC 2023
     */
    int insert(WxUserInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user_info
     *
     * @mbg.generated Fri May 12 05:53:46 UTC 2023
     */
    int insertSelective(WxUserInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user_info
     *
     * @mbg.generated Fri May 12 05:53:46 UTC 2023
     */
    List<WxUserInfoEntity> selectByExample(WxUserInfoEntity example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user_info
     *
     * @mbg.generated Fri May 12 05:53:46 UTC 2023
     */
    WxUserInfoEntity selectByPrimaryKey(Long id);
    
    WxUserInfoEntity findByOpenId(String openId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user_info
     *
     * @mbg.generated Fri May 12 05:53:46 UTC 2023
     */
    int updateByExampleSelective(@Param("record") WxUserInfoEntity record, @Param("example") WxUserInfoEntity example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user_info
     *
     * @mbg.generated Fri May 12 05:53:46 UTC 2023
     */
    int updateByExample(@Param("record") WxUserInfoEntity record, @Param("example") WxUserInfoEntity example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user_info
     *
     * @mbg.generated Fri May 12 05:53:46 UTC 2023
     */
    int updateByPrimaryKeySelective(WxUserInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user_info
     *
     * @mbg.generated Fri May 12 05:53:46 UTC 2023
     */
    int updateByPrimaryKey(WxUserInfoEntity record);
}