package com.tiyiyun.sso.entity;

import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AlipayUserInfoEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alipay_user_info.id
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alipay_user_info.merchant_id
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    private Long merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alipay_user_info.user_id
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alipay_user_info.nick_name
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alipay_user_info.open_id
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alipay_user_info.unionId
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    private String unionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alipay_user_info.gender
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alipay_user_info.province
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alipay_user_info.city
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alipay_user_info.avatar
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alipay_user_info.create_time
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alipay_user_info.update_time
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alipay_user_info.is_delete
     *
     * @mbg.generated Wed May 17 06:50:32 UTC 2023
     */
    private Integer isDelete;

}