package com.tiyiyun.sso.entity;

import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AppEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.id
     *
     * @mbg.generated Fri Mar 10 03:27:58 UTC 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.appId
     *
     * @mbg.generated Fri Mar 10 03:27:58 UTC 2023
     */
    private String appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.app_name
     *
     * @mbg.generated Fri Mar 10 03:27:58 UTC 2023
     */
    private String appName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.app_secret
     *
     * @mbg.generated Fri Mar 10 03:27:58 UTC 2023
     */
    private String appSecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.person_charge
     *
     * @mbg.generated Fri Mar 10 03:27:58 UTC 2023
     */
    private String personCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.create_time
     *
     * @mbg.generated Fri Mar 10 03:27:58 UTC 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.is_delete
     *
     * @mbg.generated Fri Mar 10 03:27:58 UTC 2023
     */
    private Integer isDelete;

}